### ISSUE TITLE
Remove Notion Brand from public pages

### ISSUE THREAD

**Issue by dixcity** [hosso/notion-custom-domain#10]
I wish there was a feature to remove the 'Try Notion' brand in the top corner of the website so that the website looks cleaner.

**Comment by iplanwebsites** [comment]
Just for a presentation, I injected a dirty hotfix via css.
Simply add this piece along the Js tracking code.
`<style>
.notion-topbar > div > .notion-focusable{
  display:none !important;
}
</style>`

**Comment by CER418** [comment]
> Just for a presentation, I injected a dirty hotfix via css. Simply add this piece along the Js tracking code. `<style> .notion-topbar > div > .notion-focusable{ display:none !important; } </style>`

On what line? Are you talking about the .ts file?

**Comment by omarcostahamido** [comment]
@bxpa ☝️ 
@hosso please see PR #18
