### ISSUE TITLE
PNG images not showing up

### ISSUE THREAD

**Issue by robertseghedi** [hosso/notion-custom-domain#11]
Hi.

I've been trying your code and there is a problem (at least for me). Maybe you can give me some tips about it.

PNG images are not really showing up. SVG's are. I can't figure it out.

**Comment by hosso** [comment]
Thank you for your report. I can't tell the cause at present, but if you could provide (a) the URL of the original page of `notion.site` and (b) the URL of the custom domain page or the URL of `vercel.app`, it would be helpful for me to investigate.

In my case:
- (a) https://fluorescent-trawler-4fe.notion.site/Notion-Custom-Domain-2a8cdabb8ab440579ca40950d79a04b5
- (b) https://notion-custom-domain.hosso.co

**Comment by robertseghedi** [comment]
> Thank you for your report. I can't tell the cause at present, but if you could provide (a) the URL of the original page of `notion.site` and (b) the URL of the custom domain page or the URL of `vercel.app`, it would be helpful for me to investigate.
> 
> In my case:
> 
> * (a) https://fluorescent-trawler-4fe.notion.site/Notion-Custom-Domain-2a8cdabb8ab440579ca40950d79a04b5
> * (b) https://notion-custom-domain.hosso.co

Sure. Here you are - https://notion-custom-domain-ten.vercel.app

**Comment by robertseghedi** [comment]
And also my Notion page - https://seghedi.notion.site/Robert-Seghedi-61068ca44c994aea803c3aeef2f3f088

**Comment by hosso** [comment]
Thanks for your information. I suppose 34d6fcdd5151f3127248cd087ad656b8f97ff92d should fix the issue. After some testing, I'll merge it into `master`.

**Comment by robertseghedi** [comment]
Yes. It worked. Nice job!

https://notion-custom-domain-ten.vercel.app/
