### ISSUE TITLE
Handle databases for landing page

### ISSUE THREAD

**Issue by youmustfight** [hosso/notion-custom-domain#12]
## Problem

I believe there is an error handling databases as the home/entry page. I get a blank page along with the following error: `Uncaught SyntaxError: Invalid regular expression flags (at app-dfa330d436d18bd4f80e.js:1:301)`

I think this is because of the [page id matching regex on line 11](https://github.com/hosso/notion-custom-domain/blob/3b493597e7a8e9356c08a38cc713cdb97e640582/src/index.ts#L11). Here is what _pagePath_ when doing a page vs database:

**Page PAGE_URL**: `https://stealthisnonprofit.notion.site/STEAL-THIS-NONPROFIT-5b1f8b9e98fb433095582219cbbe6462`
**pagePath**: `5b1f8b9e98fb433095582219cbbe6462`

**Database PAGE_URL**: `https://stealthisnonprofit.notion.site/214726270a4a44d48d0d33f2ce4a062c`
**pagePath**: `/214726270a4a44d48d0d33f2ce4a062c`

## Solution

The match function seems to expect a "-". I fixed this by simply replacing the leading slash with an empty string when matching for the page path, but not sure if this causes other problems. 

`const pageId = pagePath.replace('/', '').match(/[^-]*$/);`

Thank you for making this repo/project! It's so great and easy to spin up!

**Comment by hosso** [comment]
Thanks for the report. Also, sorry for the late response. I believe 74fdd9b1d72e3365b037efdbe7c3f9c2b0a9e8a4 should fix it.
