### ISSUE TITLE
The project seems to have failed

### ISSUE THREAD

**Issue by ShiinaRinne** [hosso/notion-custom-domain#17]
I deployed about four months ago and has been working normally. 
But yesterday, I discovered that the following error occurred during the visit:
![image](https://github.com/hosso/notion-custom-domain/assets/45081750/8200dbcd-5fbb-4570-b1f2-4dc68632934a)

I tried to add `window. CONFIG. domainBaseUrl="xxx. com"` to the `index.ts`.
 Although it can be accessed, it is currently unable to access the homepage and requires login, which may result in errors
![image](https://github.com/hosso/notion-custom-domain/assets/45081750/932c92dc-25c1-4e81-8c5c-1ee33f2f4a75)

https://easonyang.com/posts/build-a-website-with-notion/#%E8%87%AA%E5%8A%A9%E5%8F%8D%E5%90%91%E4%BB%A3%E7%90%86%E5%BB%BA%E7%AB%99
I also attempted to modify some domain in the response based on this, but it caused the Notion front-end code to judge requestedOnPublicDomain as true and carry this parameter to request whether login is required from the Notion backend, ultimately leading to a strong jump to the login page

**Comment by hosso** [comment]
Hi! Is this issue still occurring? On my [demo page](https://notion-custom-domain.hosso.co), it seems to be working properly now. If it's still happening, it would be helpful if you could share the URL of your page. The cause might be related to something on Notion side.

**Comment by ShiinaRinne** [comment]
Thanks for your reply! 
It seems to have happened accidentally. 
On the day I reported the issue, my previous website and the new one I deployed for testing were affected. 
However, after I reported the issue, it started working fine after a few days, without making any configuration changes or redeploying, I think this may be due to some issues with Notion's service that day XD

**Comment by ShiinaRinne** [comment]
Hello~
Unfortunately, it's happening again Both your demo page and my two sites cannot be used.
![image](https://github.com/hosso/notion-custom-domain/assets/45081750/8107066e-9e1b-4391-a54c-18ea02d316b4)

**Comment by OnlyKris** [comment]
same here

**Comment by mrothko2** [comment]
Any luck about how to fix it?

**Comment by hosso** [comment]
Sorry for my late reply. The location of `app-*.js` on the Notion site seems to have changed. I will consider adapting to it.

**Comment by mrothko2** [comment]
fixed! awesome! it's working now!

**Comment by omarcostahamido** [comment]
so... it is happening again, any insights?
@hosso @ShiinaRinne

**Comment by ShiinaRinne** [comment]
Sorry, I have no idea
The previous commit was also due to the author pointing out the problem, so I tried to modify it to understand the general working principle

Now it seems that Notion has written some things in a new `mainApp-*.js`. 
I tried to apply the rules of `app-*.js`, but did not get the expected results.

- previous
https://youngmoe.notion.site/_assets/app-af6bde107c9a1f7f.js
![image](https://github.com/hosso/notion-custom-domain/assets/45081750/792d2496-017c-4096-a99a-77aed008e6bf)

- now
https://youngmoe.notion.site/_assets/app-cc185934c0f77828.js
![image](https://github.com/hosso/notion-custom-domain/assets/45081750/b0a57916-c661-4e39-b11a-209d3840862c)
https://youngmoe.notion.site/_assets/mainApp-549318d0794eb586.js
![image](https://github.com/hosso/notion-custom-domain/assets/45081750/a09502f7-d8a5-4e0a-846e-6c848ed53122)

I am not familiar with JavaScript and I am not sure how to modify it. may need to wait for the author's fix

**Comment by omarcostahamido** [comment]
can you reopen the issue @ShiinaRinne ? Thank you for your report on your investigation.
applying the `/^/, `var $ncd ...` rules to `...mainApp-.*\.js$` does seem to get rid of the "Mismatch between origin and baseUrl (dev)." popup, but it does not render the page still...

**Comment by ShiinaRinne** [comment]
no,I cannot reopen it
![image](https://github.com/hosso/notion-custom-domain/assets/45081750/7eb566c0-587b-4857-87c1-cbfbf2de925b)
