### ISSUE TITLE
notion public page link have changed.

### ISSUE THREAD

**Issue by 1kuxyz** [hosso/notion-custom-domain#4]
I deploy notion-custom-domain by vercel,but it doesn't work.
I wonder, maybe because of notion public page link changed.
Before:
notion.so/abc/xxxxx12345
Now:
abc.notion.site/xxxxx12345

**Comment by hosso** [comment]
Thanks for reporting😃
To adapt to the new public link rule, I've redesigned the code at 59b5d7ce0ff98945a84c993cf20727d1783c9f03.
