### ISSUE TITLE
Auto add a suffix to the custom domain

### ISSUE THREAD

**Issue by 1kuxyz** [hosso/notion-custom-domain#5]
In vercel I created an environment variables.The name is PAGE_URL, value is https://1kuxyz.notion.site/1-xyz-s-Shop-ef43d1756d1c4d7cb49c8bc96dec3b13.
And add custom domain is [vercel.1ku.xyz](https://vercel.1ku.xyz).
After deploy, visit the custom domain site, the url will auto changed to http:/vercel.1ku.xyz/1kuxyz in address bar.
It auto add a suffix '1kuxyz' in url.
I think this suffix should be extra one.
![image.png](https://i.loli.net/2021/08/21/zrNOJvbxoZhVl7X.png)

**Comment by hosso** [comment]
I've fixed this issue at 2338be2f978eeaea1ed52cb23a31ecc69e7cab13. I found that if a user has specified his/her domain at the Notion settings page, it's automatically navigated from `/*` to `/userdomain/*` when opening the link.
