### ISSUE TITLE
The custom domain does't work on iOS

### ISSUE THREAD

**Issue by 1kuxyz** [hosso/notion-custom-domain#6]
When open https://notion-custom-domain.hosso.co by safari/chrome/edge on iOS.
You will see blank page.
![image](https://user-images.githubusercontent.com/40167317/132931408-26d2db37-6a57-4495-9193-944497d9c8a9.png)
![image](https://user-images.githubusercontent.com/40167317/132931455-82585cf3-eae4-4f0a-9ed2-45e1c4cde46b.png)

**Comment by hosso** [comment]
Thanks for your report. It seems Safari has a regexp limitation discussed here: https://stackoverflow.com/questions/51568821/works-in-chrome-but-breaks-in-safari-invalid-regular-expression-invalid-group

I fixed this issue at b8905b0e629bd3543f772e39b231551531cb1a4b.

**Comment by 1kuxyz** [comment]
Thanks for your fix
But it doesn't seem to go well.
Open https://notion-custom-domain.hosso.co on PC and iPad. Frist time the page will been opened successful,  the link will add a suffix '/https$1/$1/'. And then refresh the web page 2-3 times, it will be fail.
![image](https://user-images.githubusercontent.com/40167317/132939136-7beb8c60-d5b3-4238-addc-1b83d592a8b8.png)

**Comment by hosso** [comment]
> Open https://notion-custom-domain.hosso.co on PC and iPad. Frist time the page will been opened successful, the link will add a suffix '/https$1/$1/'. And then refresh the web page 2-3 times, it will be fail.

I expect it was fixed by 292b97beb5159b9f9c03f212ef7ce6c487b476e7.
