### ISSUE TITLE
Nice! But my cover image didn't show

### ISSUE THREAD

**Issue by unnhao** [hosso/notion-custom-domain#7]
I found a lot of services that can customize notion webpage and I found this repo to let me know how to achieve it, It's so great. But my cover image didn't show up. and I want to know how to know a lot of proxy knowledge. I found a lot of difficult code in index.ts. I just know add some style tag to hide topbar haha.

**Comment by hosso** [comment]
Hi, thank you for the report.

> But my cover image didn't show up.

On [my page](https://notion-custom-domain.hosso.co), the cover image is correctly displayed. Could you provide the URL to reproduce the issue?

> I found a lot of difficult code in index.ts. I just know add some style tag to hide topbar haha.

You might achieve that by replacing the original html like the GA snippet injection:
https://github.com/hosso/notion-custom-domain/blob/292b97beb5159b9f9c03f212ef7ce6c487b476e7/src/index.ts#L84-L86
