### ISSUE TITLE
Getting Blank Page

### ISSUE THREAD

**Issue by ilovefreesw** [hosso/notion-custom-domain#9]
Only the title appears correctly. The rest of the page is blank.

![image](https://user-images.githubusercontent.com/77317006/150639211-3de09bd0-a9dd-4100-8d20-098aacab936e.png)

What I did:

1. Imported the forked repo in Vercel
2. Created the env variable `Page_URL` and added the public notion page URL = https://silver-push-150.notion.site/Getting-Started-86b84286e165406487e88b3e30103b71 
![image](https://user-images.githubusercontent.com/77317006/150639271-b8409342-12ef-47b6-989f-54a8c5eebe6c.png)

3. Deployed.

**Comment by hosso** [comment]
Thanks for the report. It seems that something has changed on the Notion side recently. I've applied a workaround to `master` at c8fc23109d26b6780310b12fd931b4519a9b62cc. [My demo page](https://notion-custom-domain.hosso.co) is displayed correctly with the commit.

**Comment by ilovefreesw** [comment]
Works now. Thanks.

On a sidenote, can you tell me what I have to do to make the page embeddable for example in <iframe> from vercel?

**Comment by hosso** [comment]
I'm not familiar with it, but it may be possible to embed your hosted page in an iframe on another site by setting up the CSP header.

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/frame-src
